# tasks.yaml - UPGRADED FOR ELITE-LEVEL OUTPUT

research_task:
  agent: Researcher
  description: >
    **Objective:** Conduct a targeted intelligence gathering operation on the financial performance of '{topic}' for the most recent trading day.
    **Directive:** Using the `SerperDevTool`, you must extract specific, verifiable data points. Do not return general articles.
    **Required Data Points:**
    1. The stock's closing price.
    2. The percentage change for the day (e.g., +1.5% or -2.1%).
    3. The day's trading volume.
    4. The top 2-3 news headlines or market events that were cited as the primary drivers for the stock's movement.
  expected_output: >
    A structured data report in Markdown. It must contain only the extracted facts, each with a source URL.
    Example:
    - Closing Price: $120.50 (Source: https://...)
    - Daily Change: +3.2% (Source: https://...)
    - Volume: 95M (Source: https://...)
    - Key Driver: "NVIDIA announced a new AI chip partnership." (Source: https://...)

summary_writer_task:
  agent: SummaryWriter
  description: >
    **Objective:** Receive the structured data report from the 'Researcher' and transform it into a high-impact, strategic narrative for our 'afterUsMarket' channel.
    **Directive:** Your brief must be concise, insightful, and answer "Why did this happen and what does it mean?".
    The language must be professional and immediately understandable.
  expected_output: >
    A polished, executive-ready brief in Markdown. The report must strictly follow this structure:
    1. **Title:** A powerful, descriptive title (e.g., `# NVDA Daily Debrief: Surges on AI Partnership News`).
    2. **Top-Line Summary:** A single sentence summarizing the outcome (e.g., `NVIDIA (NVDA) closed at $120.50, a significant gain of +3.2% on high trading volume.`).
    3. **Key Drivers:** A bulleted list explaining the 'why' behind the movement, directly linking the news to the performance.
    
visualization_task:
  agent: Visualizer
  description: >
    **Objective:** Create a professional, data-driven visual asset that summarizes the key financial metric for '{topic}'.
    **Directive:** Your sole focus is to craft the perfect, expert-level prompt for the `ImageGenerationTool` to produce a clean, informative chart, and then execute it. The visual must be of professional, financial-report quality.
    For example, if the topic is a stock's daily performance, the prompt you generate should be something like:
    "A professional and minimalist financial data visualization for a Telegram dark mode theme. Create a clean bar chart titled 'NVIDIA (NVDA) Daily Snapshot'. It must clearly show the closing price of [$120.50] and the daily percentage change of [+3.2%]. Use a vibrant green color for the percentage change to indicate a positive gain. The style should be modern, with sharp fonts, similar to a Bloomberg terminal graphic. No unnecessary clutter."
  expected_output: >
    A mission success confirmation string that explicitly states: "'image.png' has been successfully generated and is ready for immediate dispatch."

translation_task:
  # This task is already well-defined, no changes needed unless you want to specify a financial tone.
  agent: translator
  description: >
    Mission Briefing for the Diplomatic Corps Linguist ('Babel'):
    Your objective is to perform a full linguistic and cultural adaptation of the
    strategic narrative on '{topic}' into '{language}'. The final translated text
    must be flawless and ready for immediate publication or diplomatic briefing.
    Maintain the authority and nuance of the original source.
  expected_output: >
    The complete, translated strategic narrative in Markdown format. The output
    must be free of any grammatical errors and must read as if it were originally
    authored by a native speaker of '{language}'.
  dependencies: [summary_writer_task]
  async_execution: true

send_summary_task:
  agent: telegram_sender
  description: >
    **Objective:** Deliver the final text-based strategic narrative to the Telegram channel.
    **Directive:** Use the `SendTextInTelegramChannel` tool to transmit the complete, polished brief you receive from the previous task. This is the main text body of our market report.
  expected_output: >
    A delivery confirmation report containing the raw API response from the Telegram service, confirming the successful transmission of the text message.
  dependencies: [summary_writer_task, translation_task]

send_image_task:
  agent: telegram_sender
  description: >
    **Objective:** Deliver the final visual asset to the Telegram channel.
    **Directive:** Use the `SendImageInTelegramChannel` tool to transmit the 'image.png' file. This visual component is critical and must accompany the text report.
  expected_output: >
    A delivery confirmation report containing the raw API response from the Telegram service, confirming the successful transmission of the image.
  dependencies: [visualization_task]